<?php
/***************************************************************************
 * Extension Name    : Bestseller Products
 * Extension URL    : http://www.magebees.com/magento-bestseller-products-extension.html
 * Copyright        : Copyright (c) 2015 MageBees, http://www.magebees.com
 * Support Email    : support@magebees.com
 ***************************************************************************/
?>
<?php
$result = array();
$pro = array();
$bestseller_collection = $this->getBestsellerProduct();
foreach ($bestseller_collection as $collection) {
    $pro[] = $collection->getEntityId();
}
if ($this->getChooseProducts() == "1") {
    $result = $pro;
} elseif ($this->getChooseProducts() == "2") {
    $result = $this->getProductIds();
} else {
    if ($this->getSortOrder() == 1) {
        $result = array_unique(array_merge($pro, $this->getProductIds()));
    } elseif ($this->getSortOrder() == 2) {
        $result = array_unique(array_merge($this->getProductIds(), $pro));
    } else {
        $result = array_unique(array_merge($pro, $this->getProductIds()));
        shuffle($result);
    }
}
$upperLimit = ($this->getLimit()) ? $this->getLimit() : 1;
$itemPerRow = ($this->getItemsPerRow()) ? $this->getItemsPerRow() : 1;
?>
<?php if ($this->getEnabled()): ?>
    <?php if ($this->getDisplayHeader()): ?>
        <div class="top_main">
            <h2><?php if (count($result) > 0) {
                    echo $this->getHeader();
                } ?></h2>
            <a href="#">show all</a>
            <div class="clear"></div>
        </div>
    <?php endif; ?>
    <div class="grids_of_3">
        <?php
        $i = 0;
        $x = 1;
        foreach ($result as $result) {
            $_product = $this->getProducts($result);
            if (!$_product) {
                continue;
            }
            if ($x <= $upperLimit) {
                if ($i > ($itemPerRow - 1))
                    echo '<tr valign="top">';
                ?>
                <div class="grid1_of_3">
                    <a href="<?php echo $this->getBaseUrl() . $_product['url_path']; ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
                        <img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(220) ?>"
                             alt="<?php echo $this->htmlEscape($_product['name']) ?>"/>
                        <h3><?php echo $this->htmlEscape($_product['name']) ?></h3>
                        <div align="center">
                            <div class="prodDetails">

                                <?php
                                if ($this->getReview()) {
                                    $_product = Mage::getModel('catalog/product')->load($_product->getId());
                                    echo $this->getReviewsSummaryHtml($_product, 'short');
                                }
                                if ($this->getProductsPrice()) {
                                    $_product = Mage::getModel('catalog/product')->load($_product->getId());
                                    echo $this->getPriceHtml($_product, true);
                                }
                                ?>
                            </div>
                            <?php if ($this->getAddToCart()): ?>
                                <?php if ($_product->isSaleable()): ?>
                                    <button class="button btn-cart"
                                            onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')">
                                        <span><?php echo $this->__('Add to Cart') ?></span></button>
                                <?php else: ?>
                                    <span class="out-of-stock"><?php echo $this->__('Out of stock') ?></span>
                                <?php endif; ?>
                            <?php endif; ?>
                        </div>
                    </a>


                </div>
                <?php if ($this->getActive()): ?>
                    <div class="cl">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                            <a href="<?php echo $this->getAddToWishlistUrl($_product) ?>" class="addWishlist">
                                <?php echo $this->__('Add to Wishlist') ?>
                            </a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if ($this->getAddToCompare()): ?>
                    <div class="cl">
                        <?php if ($_compareUrl = $this->getAddToCompareUrl($_product)): ?>
                            &nbsp;<a href="<?php echo $_compareUrl; ?>"
                                     class="addCompare"><?php echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php
                $i++;
                if ($i > ($itemPerRow - 1)) {
                    $i = 0;
                    echo "</tr>";
                    echo '<tr><td colspan="3" class="hline"><img src="' . $this->getSkinUrl('images/spacer.gif') . '" alt="" /></td></tr>';
                }
                if ($i == ($itemPerRow)) {
                    echo '<td class="vline"><img src="' . $this->getSkinUrl('images/spacer.gif') . '" alt=""/></td>';
                }
            }
            $x++;
        }
        ?>
    </div>
<?php endif; ?>